[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "MGitPython"
version = "0.8.0"
dependencies = [
    "fire",
    "jinja2",
    "pyyaml",
    "setuptools",
]

[project.scripts]
cli-name = "mgitpy:main"
